### PR TITLE
Feature/add slider

### PR DESCRIPTION
**Pull request by claudio-moya**

### CODE REVIEW

**Comment by claudio-moya** [comment]
- [ ] Use fixed versions of dependencies, avoid the `^` before the packages versions

https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/package.json#L34-L35

- [ ] Slider is triggering a warning on all samples except for slider page.

Screen Shot 2021-01-21 at 14 31 46

- [ ] Max value validation is not working on initial load, only works once you click on the slider

Screen Shot 2021-01-21 at 14 42 57

- [ ] `showValue: false,` prop is not working

Screen Shot 2021-01-21 at 14 45 11
Screen Shot 2021-01-21 at 14 45 27

- [ ] `isSelector` variable name should refer to a boolean value (true/false), use another name to manage the selector props

https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L13

Not OK
`isSelector.style.width = `${width}px`;`

OK
`domSelector.style.width = `${width}px`;`

- [ ]  Due to the build code using babel will be ES5, if you use `let` , `var` should not be used, (same for the functions notation `() =>` ) decide which one is the rule.

- [ ]  Don't add functions inside the function without checking the return value.

https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L109-L128

- [ ] Organize the events for `slider` and `thumb`, don't mix them one after other, examples:

Not OK

```
thumb.ondragstart = function () {
      return false;
    };

    slider.addEventListener("touchstart", function(e){
      if (e.cancelable) {
        e.preventDefault();
      }
      e.stopPropagation();

      changeHandler(e);

      document.addEventListener("touchmove", changeHandler);
      document.addEventListener("touchend", function () {
        if (e.cancelable) {
          e.preventDefault();
        }
        e.stopPropagation();

        document.removeEventListener("touchmove", changeHandler);
        thumb.removeEventListener("touchstart", changeHandler);

        thumb.classList.remove("active");
      });
    });

    thumb.addEventListener("focus", () => {
      thumb.addEventListener("keydown", onKeydown);
      thumb.addEventListener("blur", () => thumb.removeEventListener("keydown", onKeydown));
    });
```

OK

```
 // all on events for slider
    slider.addEventListener("touchstart", function(e){
      if (e.cancelable) {
        e.preventDefault();
      }
      e.stopPropagation();

      changeHandler(e);

      document.addEventListener("touchmove", changeHandler);
      document.addEventListener("touchend", function () {
        if (e.cancelable) {
          e.preventDefault();
        }
        e.stopPropagation();

        document.removeEventListener("touchmove", changeHandler);
        thumb.removeEventListener("touchstart", changeHandler);

        thumb.classList.remove("active");
      });
    });

 // all on events for thumb
    thumb.ondragstart = function () {
      return false;
    };

    thumb.addEventListener("focus", () => {
      thumb.addEventListener("keydown", onKeydown);
      thumb.addEventListener("blur", () => thumb.removeEventListener("keydown", onKeydown));
    });

 // the other addEventListener for thumb
```

**Comment by htanjo** [comment]
# 1. Bugs
### 1.1. "min" option doesn't work.
Min value is forced to 0.

### 1.2. Device detection potentially doesn't work.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L103

`window.ontouchstart` can be a function if it's already defined. Please refer implementation of major libraries.

### 1.3. Drag doesn't work correctly when page is horizontally scrolled.
`.pageX` should be `.clientX`. Refer: https://qiita.com/yukiB/items/31a9e9e600dfb1f34f76

### 1.4. Events can be duplicated.
Probably some `.removeEventListener()` is missing or not working.

image

### 1.5. limitRange() called twice on touch devices.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L128-L136

### 1.6. Initial value is not comma-separated.
The tooltip should be "1,000".

image

# 2. Programming issues
### 2.1. Can be simplified.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L2-L11
```js
const {
  selector = null,
  min = 0,
  ...
} = input || {};
```

### 2.2. Use efficient selectors.
- `document.querySelector(selector)` appears several times. Make it into variable.
- Bad: ``document.querySelector(`${selector} .rex-slider`)``, Good: `element.querySelector('.rex-slider')`

### 2.3. Use efficient styles.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L40-L42

Better:
```
thumb.style.left = `${position - thumb.offsetWidth / 2}px`;
```

Best:
```
thumb.style.transform = `translateX(${position}px)`;
```

### 2.4. Separate business logic from DOM.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L64

Current value should be stored in a variable. Don't depend on DOM.

### 2.5. Inconsistent coding style
Use consistent coding style.

- Quotations: `"`, `'`
- Variables: `var`, `let` -> should use `const` and `let`.
- Functions: `function xxx() {...}`, `var xxx = function () {...}`
- Events: `.addEventListener(...)`, `.ondragstart = ...`

### 2.6. Unused return value.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L125

### 2.7. Undesirable implementation.
Consider another way.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L131-L132

### 2.8. Don't repeat the same code.
- `if (document.querySelector(selector).classList.contains('disabled')) {`
- `thumb.addEventListener("focusout", () => `
- L153〜 (mouse event), L175〜 (touch event)

### 2.9. Use proper event.
- "focusout" vs "blur"
  - focus <-> blur, focusin <-> focusout
  - https://developer.mozilla.org/ja/docs/Web/API/Element/focusout_event

### 2.10. Use idiomatic functions.
Prioritize readability and maintainability.

Bad:
```
refValue(currentVal + 1);
refPosition(calcPositionByValue(currentVal + 1));
```

Good:
```
setValue(currentVal + 1);
```

# 3. Behavior issues
### 3.1. Should support multiple elements.
`rexSlider({ selector: '.slider' })` will create a slider only for the first matched element.

This line should be `querySelectorAll()`.
https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L13

### 3.2. Should support negative value
Current implementation doesn't take care of negative values. e.g. from -100 to 100

### 3.3. Don't use class="disabled" to define disabled state.
Class attribute is mainly used for styles. To define state, use JavaScript option or data attributes.

### 3.4. Not able to get value from outside.

### 3.5. Not able to listen change event from outside.

### 3.6. Not able to disable or enable slider after initialize.

### 3.7. (Minor) Not compatible with liquid layout.

### 3.8. Support customization by data attributes.
It's convenient for user to produce various slider with single code.

Customize by options:
```html
<div id="slider-1"></div>
<div id="slider-2"></div>
<div id="slider-3"></div>
<script>
  rexSlider({
    selector: "#slider-1",
    initial: 10
  });
  rexSlider({
    selector: "#slider-2",
    initial: 20
  });
  rexSlider({
    selector: "#slider-3",
    initial: 30
  });
</script>
```

Customize by data attributes:
```html
<div class="slider" data-initial="10"></div>
<div class="slider" data-initial="20"></div>
<div class="slider" data-initial="30"></div>
<script>
  rexSlider({
    selector: ".slider"
  });
</script>
```

# 4. Suggestions
### 4.1. Add more UI patterns to test all of options.
We can prevent bugs before review. 

### 4.2. Install ESLint and Prettier for better coding.
We can standardize code style and prevent some bugs.

### 4.3. Define spec of component.
We can review the component from user points of view. We can test possible behaviors clearly.

### 4.4 Start from more simple component.
We can focus on basic and common implementations. (e.g. customization, outside linkage)

# 5. What I didn't
- Browser compatibility test.
- Review of styles.

**Comment by montomos** [comment]
> * [ ]  Use fixed versions of dependencies, avoid the `^` before the packages versions
> 
> https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/package.json#L34-L35
> 
> * [ ]  Slider is triggering a warning on all samples except for slider page.
> 
> Screen Shot 2021-01-21 at 14 31 46
> 
> * [ ]  Max value validation is not working on initial load, only works once you click on the slider
> 
> Screen Shot 2021-01-21 at 14 42 57
> 
> * [ ]  `showValue: false,` prop is not working
> 
> Screen Shot 2021-01-21 at 14 45 11
> Screen Shot 2021-01-21 at 14 45 27
> 
> * [ ]  `isSelector` variable name should refer to a boolean value (true/false), use another name to manage the selector props
> 
> https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L13
> 
> Not OK
> `isSelector.style.width = `${width}px`;`
> 
> OK
> `domSelector.style.width = `${width}px`;`
> 
> * [ ]   Due to the build code using babel will be ES5, if you use `let` , `var` should not be used, (same for the functions notation `() =>` ) decide which one is the rule.
> * [ ]   Don't add functions inside the function without checking the return value.
> 
> https://github.com/rakuten-rex/styles/blob/5b6bc4a9358d8138c2d7835a74222bd282b931e2/src/modules/rexSlider.js#L109-L128
> 
> * [ ]  Organize the events for `slider` and `thumb`, don't mix them one after other, examples:
> 
> Not OK
> 
> ```
> thumb.ondragstart = function () {
>       return false;
>     };
> 
>     slider.addEventListener("touchstart", function(e){
>       if (e.cancelable) {
>         e.preventDefault();
>       }
>       e.stopPropagation();
> 
>       changeHandler(e);
> 
>       document.addEventListener("touchmove", changeHandler);
>       document.addEventListener("touchend", function () {
>         if (e.cancelable) {
>           e.preventDefault();
>         }
>         e.stopPropagation();
> 
>         document.removeEventListener("touchmove", changeHandler);
>         thumb.removeEventListener("touchstart", changeHandler);
> 
>         thumb.classList.remove("active");
>       });
>     });
> 
>     thumb.addEventListener("focus", () => {
>       thumb.addEventListener("keydown", onKeydown);
>       thumb.addEventListener("blur", () => thumb.removeEventListener("keydown", onKeydown));
>     });
> ```
> 
> OK
> 
> ```
>  // all on events for slider
>     slider.addEventListener("touchstart", function(e){
>       if (e.cancelable) {
>         e.preventDefault();
>       }
>       e.stopPropagation();
> 
>       changeHandler(e);
> 
>       document.addEventListener("touchmove", changeHandler);
>       document.addEventListener("touchend", function () {
>         if (e.cancelable) {
>           e.preventDefault();
>         }
>         e.stopPropagation();
> 
>         document.removeEventListener("touchmove", changeHandler);
>         thumb.removeEventListener("touchstart", changeHandler);
> 
>         thumb.classList.remove("active");
>       });
>     });
> 
>  // all on events for thumb
>     thumb.ondragstart = function () {
>       return false;
>     };
> 
>     thumb.addEventListener("focus", () => {
>       thumb.addEventListener("keydown", onKeydown);
>       thumb.addEventListener("blur", () => thumb.removeEventListener("keydown", onKeydown));
>     });
> 
>  // the other addEventListener for thumb
> ```

**Comment by montomos** [comment]
> * , (same for the functions notation `() =>` ) decide which one is the rule.

Could you give me the details about this part?
Do you mean something like regular functions and arrow function shouldn't be mixed?

If you replace every function syntax with arrow functions, it's not going to work in all cases.

**Comment by claudio-moya** [comment]
> > * , (same for the functions notation `() =>` ) decide which one is the rule.
> 
> Could you give me the details about this part?
> Do you mean something like regular functions and arrow function shouldn't be mixed?
> 
> If you replace every function syntax with arrow functions, it's not going to work in all cases.

If in the current codebase doesn't work, it means that the code is not correct.

Take a look to the build code at `dist` folder, all functions are converted to ES5.

In the code there is a mix between ES5 and ES6, you guys have to choose which one is the one to follow as code base.

**Pull request closed without merging**
